//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompagnieAssurance
    {
        public CompagnieAssurance()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int IdCompagnie { get; set; }
        public string NomCompagnie { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
