//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public Departement()
        {
            this.Lit1 = new HashSet<Lit1>();
        }
    
        public int IdDepartement { get; set; }
        public string NomDepartement { get; set; }
    
        public virtual ICollection<Lit1> Lit1 { get; set; }
    }
}
