//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierAdmission
    {
        public int IdAdmission { get; set; }
        public string ChirurgieProgramme { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
        public Nullable<System.DateTime> DateChirurgie { get; set; }
        public Nullable<System.DateTime> DateConge { get; set; }
        public Nullable<int> IdPatient { get; set; }
        public Nullable<int> NumeroLit { get; set; }
        public string Commodite { get; set; }
    
        public virtual Lit1 Lit1 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
