//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lit1
    {
        public Lit1()
        {
            this.DossierAdmissions = new HashSet<DossierAdmission>();
        }
    
        public int NumeroLit { get; set; }
        public string Occupe { get; set; }
        public Nullable<int> NumeroType { get; set; }
        public Nullable<int> IdDepartament { get; set; }
    
        public virtual Departement Departement { get; set; }
        public virtual ICollection<DossierAdmission> DossierAdmissions { get; set; }
        public virtual TypeLit TypeLit { get; set; }
    }
}
