//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NHLEntities : DbContext
    {
        public NHLEntities()
            : base("name=NHLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompagnieAssurance> CompagnieAssurances { get; set; }
        public DbSet<Departement> Departements { get; set; }
        public DbSet<DossierAdmission> DossierAdmissions { get; set; }
        public DbSet<Lit1> Lit1 { get; set; }
        public DbSet<Medicin> Medicins { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Prepose> Preposes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TableUser> TableUsers { get; set; }
        public DbSet<TypeLit> TypeLits { get; set; }
    }
}
