//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.DossierAdmissions = new HashSet<DossierAdmission>();
        }
    
        public int IdPatient { get; set; }
        public string NSS { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string TypePatient { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> IdMedicin { get; set; }
        public Nullable<int> IdCompagnie { get; set; }
        public Nullable<int> RefParent { get; set; }
    
        public virtual CompagnieAssurance CompagnieAssurance { get; set; }
        public virtual ICollection<DossierAdmission> DossierAdmissions { get; set; }
        public virtual Medicin Medicin { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
